AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda project for use with court lambda-functions

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: court/lambdas/
      Handler: user.lambda_hello
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: court/lambdas/
      Handler: user.lambda_register
      Runtime: python3.9
      Events:
        Register:
          Type: Api
          Properties:
            Path: /register
            Method: GET

  # todo: prove this out and make sure everything else works
  GooglePlacesProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: court/lambdas/
      Handler: proxy.lambda_google_places_proxy
      Runtime: python3.9
      Environment:
        Variables:
          GOOGLE_PLACES_API_KEY: "your_google_api_key"
      Events:
        GooglePlacesProxy:
          Type: Api
          Properties:
            Path: /google-places
            Method: POST
