AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda project for use with court lambda-functions

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: true

Resources:
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/api_user/
      Handler: api_user.lambda_register
      Runtime: python3.10
      Events:
        Register:
          Type: Api
          Properties:
            Path: /register
            Method: POST

  GooglePlacesProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/api_location/
      Handler: api_location.lambda_google_places_proxy
      Runtime: python3.10
      # Environment:
      #   Variables:
      #     GOOGLE_PLACES_API_KEY: '{{resolve:secretsmanager:MySecretName:SecretString:APIKey}}'
      Events:
        GooglePlacesProxy:
          Type: Api
          Properties:
            Path: /google-places
            Method: POST
